//Users

###
GET http://localhost:4000/users/users

###
GET http://localhost:3000/users/users/1


###
DELETE http://localhost:4000/users/users/4

###
POST http://localhost:3000/users/users
Content-Type: application/json

{
  "name": "Cyrus",
  "contact_phone": "0722227154",
  "phone_verified": true,
  "email": "cyruskimtai@gmail.com",
  "email_verified": true,
  "confirmation_code": "10005",
  "password": "@cyrusKim",
  "created_at": "2024-02-01",
  "updated_at": "2024-04-01"
}
###
PUT http://localhost:3000/users/users
  {
  "name": "Cyrus",
  "contact_phone": "0722227154",
  "phone_verified": true,
  "email": "cyruskimtai@gmail.com",
  "email_verified": true,
  "confirmation_code": "10005",
  "password": "@cyrusKim",
  "created_at": "2024-02-01",
  "updated_at": "2024-04-01"
}
### Login to user
POST http://localhost:4000/users/login
Content-Type: application/json 

{
  "email": "cyruskimtai@gmail.com",
  "password": "@cyrusKim"
  
}

###







//Address 

###
GET http://localhost:3000/address/address

###
GET http://localhost:3000/address/address/2


###
DELETE http://localhost:3000/address/address/1

###
PUT http://localhost:3000/address/address
Content-Type: application/application/json
{
  "street_address_1": "300",
  "street_address_2": "20901",
  "zip_code": "20001",
  "delivery_instructions": "After payment",
  "user_id": 1,
  "city_id": 3,
  "created_at": "2024-03-05T00:00:00.000Z",
  "updated_at": "2024-03-08T00:00:00.000Z"
}
###
PUT http://localhost:3000/address/address/1



//Category 

###
GET http://localhost:3000/category/category

###
GET http://localhost:3000/category/category/2


###
DELETE http://localhost:3000/category/category/1

###
POST http://localhost:3000/category/category
content-type: application/json
{
  "name": "drinks", 
}
###
PUT http://localhost:3000/category/category/1
content-type: application/json
{
  "name": "drinks",  
}


//City 

###
GET http://localhost:3000/city/city

###
GET http://localhost:3000/city/city/3


###
DELETE http://localhost:3000/city/city/1

###
POST http://localhost:3000/city/city
content-Content-Type: application/json
{
  "name": "Nairobi",  
  "state_id": 8
}
###
PUT http://localhost:3000/city/city/1
content-Content-Type: application/json
{
  "name": "Nairobi",  
  "state_id": 8
}



//Comments 

###
GET http://localhost:3000/comments/comments

###
GET http://localhost:3000/comments/comments/1


###
DELETE http://localhost:3000/comments/comments/1

###
POST http://localhost:3000/comments/comments

###
PUT http://localhost:3000/comments/comments/1

//drivers 

###
GET http://localhost:3000/drivers/drivers

###
GET http://localhost:3000/drivers/drivers/1


###
DELETE http://localhost:3000/drivers/drivers/1

###
POST http://localhost:3000/drivers/drivers

###
PUT http://localhost:3000/drivers/drivers/1


//menu_item 

###
GET http://localhost:3000/menu_item/menu_item

###
GET http://localhost:3000/menu_item/menu_item/1


###
DELETE http://localhost:3000/menu_item/menu_item/1

###
POST http://localhost:3000/menu_item/menu_item

###
PUT http://localhost:3000/menu_item/menu_item/1



//order_menu_item 

###
GET http://localhost:3000/order_menu_item/order_menu_item

###
GET http://localhost:3000/order_menu_item/order_menu_item/1


###
DELETE http://localhost:3000/order_menu_item/order_menu_item/1

###
POST http://localhost:3000/order_menu_item/order_menu_item

###
PUT http://localhost:3000/order_menu_item/order_menu_item/1

//orders 

###
GET http://localhost:3000/orders/orders

###
GET http://localhost:3000/orders/orders/1


###
DELETE http://localhost:3000/orders/orders/1

###
POST http://localhost:3000/orders/orders

###
PUT http://localhost:3000/orders/orders/

//orders_status 

###
GET http://localhost:3000/orders_status/orders_status

###
GET http://localhost:3000/orders_status/orders_status/1


###
DELETE http://localhost:3000/orders_status/orders_status/1

###
POST http://localhost:3000/orders_status/orders_status

###
PUT http://localhost:3000/orders_status/orders_status/orders_status/1


//restautant 

###
GET http://localhost:3000/restautant/restautant

###
GET http://localhost:3000/restautant/restautant/1


###
DELETE http://localhost:3000/restautant/restautant/1

###
POST http://localhost:3000/restautant/restautant

###
PUT http://localhost:3000/restautant/restautant/restautant/1

//restaurant_owner 

###
GET http://localhost:3000/restaurant_owner/restaurant_owner

###
GET http://localhost:3000/restaurant_owner/restaurant_owner/1


###
DELETE http://localhost:3000/restaurant_owner/restaurant_owner/1

###
POST http://localhost:3000/restaurant_owner/restaurant_owner

###
PUT http://localhost:3000/restaurant_owner/restaurant_owner/1

//state 

###
GET http://localhost:3000/state/states

###
GET http://localhost:3000/state/states/1


###
DELETE http://localhost:3000/state/states/1

###
POST http://localhost:3000/state/state

###
PUT http://localhost:3000/state/state/1

//status_catalog 

###
GET http://localhost:3000/status_catalog/status_catalog

###
GET http://localhost:3000/status_catalog/status_catalog/1


###
DELETE http://localhost:3000/status_catalog/status_catalog/1

###
POST http://localhost:3000/status_catalog/status_catalog

###
PUT http://localhost:3000/status_catalog/status_catalog/1

